# Generated by Django 3.2 on 2021-11-17 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('music_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('album_name', models.CharField(default='Single', max_length=200)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='musics/')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('artist', models.ManyToManyField(to='Home.Artist')),
                ('category', models.ManyToManyField(to='Home.Category')),
                ('playlist', models.ManyToManyField(to='Home.PlayList')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
