# Generated by Django 3.2 on 2021-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagemodel',
            name='artist',
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='artist',
            field=models.CharField(default='Post Malone', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
