# Generated by Django 3.2 on 2021-11-17 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211117_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('music_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.CharField(max_length=200)),
                ('album_name', models.CharField(default='Single', max_length=200)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='musics/')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ManyToManyField(to='Home.Category')),
                ('playlist', models.ManyToManyField(to='Home.PlayList')),
            ],
        ),
    ]
