# Generated by Django 3.2 on 2021-11-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
