# Generated by Django 3.2 on 2021-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_delete_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemodel',
            name='audio_link',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
