# Generated by Django 3.2 on 2021-11-18 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_homepagemodel_audio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/Albums/')),
                ('zip_file_link', models.CharField(max_length=1200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ManyToManyField(to='Home.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
