# Generated by Django 3.2 on 2021-11-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
